In [1]:
import numpy as np

In [16]:
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
c = [x for x in range(100, 501, 100)]

In [30]:
the_array = np.array(a)
print(the_array.shape)
print(a)
a_T = np.transpose(the_array)
print(a_T)
print(a_T.shape)

(5,)
[1, 2, 3, 4, 5]
[1 2 3 4 5]
(5,)


In [34]:
array2 = np.array([a, b])
print(array2)
print(array2.shape)
print(array2.ndim)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
(2, 5)
2


In [35]:
array3 = np.array([a, b, c])
print(array3)
print(array3.shape)
print(array3.ndim)

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]
(3, 5)
2


In [38]:
d = [-x for x in range(1, 6)]
array4 = np.array([[a, b], [c,d]])
print(array4)
print(array4.shape)
print(array4.ndim)

[[[  1   2   3   4   5]
  [ 10  20  30  40  50]]

 [[100 200 300 400 500]
  [ -1  -2  -3  -4  -5]]]
(2, 2, 5)
3


In [42]:
for line in array4:
    print(line)
    print(len(line))
    for l in line:
        print()
        print(l)
        print(len(l))

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
2

[1 2 3 4 5]
5

[10 20 30 40 50]
5
[[100 200 300 400 500]
 [ -1  -2  -3  -4  -5]]
2

[100 200 300 400 500]
5

[-1 -2 -3 -4 -5]
5


# TILE

In [52]:
a = np.tile(2, (10, 2))
print('dimensions: ', a.ndim)
print('shape: ', a.shape)
print(a)

dimensions:  2
shape:  (10, 2)
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


In [53]:
b = np.tile(1, (2, 10))
print('dimensions: ', b.ndim)
print('shape: ', b.shape)
print(b)

dimensions:  2
shape:  (2, 10)
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
